name: Waka Readme

on:
  workflow_dispatch: # for manual workflow trigger
  schedule:
    - cron: '0 0 * * *' # runs at every 12AM UTC

jobs:
  update-readme:
    name: WakaReadme DevMetrics
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Sara-Pak/waka-readme@master
        with:
          REPOSITORY: Sara-Pak/Sara-Pak
          WAKATIME_API_KEY: ${{ secrets.waka_76302c8c-48a3-4e60-9ac2-ddd6b203daea }}
          GH_TOKEN: ${{ secrets.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  }}
          PATH: ./.github/actions/Sara-Pak
          USES: ./.github/actions/Sara-Pak/waka-readme
          SHOW_TITLE: true
          BLOCKS: ~♥
          TIME_RANGE: last_30_days
          SHOW_TIME: true
          SHOW_MASKED_TIME: true
          
          # following flags are required, only if this is not on
          # profile readme, remove the leading `#` to use them
          #GH_TOKEN: ${{ secrets.GH_TOKEN }}
          #REPOSITORY: <gh_username/gh_username>                    
